[book]
authors = ["erhant"]
language = "en"
multilingual = false
src = "content"
title = "Baeknote + typst"
description = "Your Description"

# KaTeX, mermaid, toc are not necessary

[preprocessor.typst]
command = "python compile_typst.py"

[output]

[output.html]
additional-css = ["./utilities/custom.css"]
git-repository-url = "https://github.com/Bubbler-4/baeknote-typst-test"
git-repository-icon = "fa-github-alt"
no-section-label = true
default-theme = "rust"
preferred-dark-theme = "navy"
site-url = "/baeknote-typst-test/"

[output.html.fold]
enable = true
level = 0

[output.html.search]
enable = true
heading-split-level = 1
boost-paragraph = 0
teaser-word-count = 0

[output.html.print]
enable = false
