[book]
authors = ["erhant"]
language = "en"
multilingual = false
src = "content"
title = "Baeknote + typst"
description = "Your Description"

# KaTeX, mermaid, toc are not necessary

[preprocessor.typst]
command = "python compile_typst.py"

[output]

[output.html]
git-repository-url = "https://github.com/Bubbler-4/baeknote-typst-test"
git-repository-icon = "fa-github-alt"
no-section-label = true
default-theme = "rust"
preferred-dark-theme = "navy"
