# https://github.com/rust-lang/mdBook/wiki/Automated-Deployment%3A-GitHub-Actions
name: your.url.here

# https://github.com/orgs/vercel/discussions/3307
# env:
#   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push: # this will trigger on every push to main branch
  # workflow_dispatch: # you will manually dispatch the workflow
    branches:
      - main
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12 #install the python needed
          
      # - name: Execute Summary-gen
      #   run: python summary_gen.py

      - name: Install mdbook
        uses: extractions/setup-crate@v1
        with:
          owner: rust-lang
          name: mdBook

      - name: Install typst
        uses: extractions/setup-crate@v1
        with:
          owner: typst
          name: typst

      - name: Generate static content for the book
        run: mdbook build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'book'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # - name: Setup Node.js (required to install Vercel CLI)
      #   uses: actions/setup-node@v3

      # - name: Install Vercel CLI
      #   run: npm install --global vercel

      # - name: Pull Vercel environment information
      #   run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Deploy to Vercel
      #   run: vercel book --prod --token=${{ secrets.VERCEL_TOKEN }}